Fix behavior for somevalue snaks
Somevalue snaks have no datavalue, so the current code dies with e.g.
_TypeError: claims.P570[0].mainsnak.datavalue is undefined_.

We need to check everything exists prior to using the value; refactored a bit to share the code without too much repeating.